# {{DOMAIN}} HTTP virtual host
<VirtualHost *:80>
    ServerName {{DOMAIN}}
    ServerAlias www.{{DOMAIN}}
    DocumentRoot {{DOCROOT}}

    <Directory {{DOCROOT}}>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/{{SAFE_NAME}}_error.log
    CustomLog ${APACHE_LOG_DIR}/{{SAFE_NAME}}_access.log combined
</VirtualHost>
